name: Redacted COVID Check

on:
  schedule:
    - cron: "00 8 * * *"
    - cron: "00 23 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run script to check Redacted Rosters
        run: |
          python -m redacted.redacted_covid_roster_check ${{ secrets.YAHOO_CLIENT_ID }} ${{ secrets.YAHOO_CLIENT_SECRET }} ${{ secrets.YAHOO_REFRESH_TOKEN }}
      - name: Read roster_report.txt
        id: report
        uses: juliangruber/read-file-action@v1
        with:
          path: ./roster_report.txt
      - name: Send Discord Notifcation
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: ${{ steps.report.outputs.content }}
