name: Update Rosters

on:
  push:
    branches: [ trunk ]
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Decrypt Secrets
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ACCOUNT_SERVICE_PASSWORD }}" --output sheets/service_account.json secret.gpg
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run script to update Sheets
        run: python -m yahoo.update_individual_rosters_main  ${{ secrets.YAHOO_CLIENT_ID }} ${{ secrets.YAHOO_CLIENT_SECRET }} ${{ secrets.YAHOO_REFRESH_TOKEN }}
