name: Update Main Data Page

#on:
#  schedule:
#    - cron: "0 6 * * *"

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Decrypt Secret
        run: |
          echo "${{ secrets.ACCOUNT_SERVICE }}" > service_account.json.asc
          gpg -d -passphrase "${{ secrets.ACCOUNT_SERVICE_PASSWORD }}" --batch service_account.json.asc > sheets/service_account.json
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install GeckoDriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
          mkdir geckodriver
          tar -xzf geckodriver-v0.28.0-linux64.tar.gz -C geckodriver
          export PATH=$PATH:$PWD/geckodriver
      - name: Run script to update Sheets
        run: python basketball_monster/basketball_monster_main.py

