name: Update Team Names

on:
  schedule:
    - cron: "00 6 * * 1"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Create Yahoo Access Key
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.YAHOO_KEYS_PASSWORD }}" --output yahoo/.yahoofantasy yahoo.gpg
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run script to update Sheets
        run: python -m yahoo.update_team_name_main
